spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 147258
    url: jdbc:mysql://localhost:3306/liyaoyun
  application:
    name: user_centre
  session:
    timeout: 86400

